import random

def Compliment():
    """
    Gives a random compliment.
    @example
    print(Communication.Compliment())
    """

    Compliments = [
        'Your smile is contagious.',
        'I bet you make babies smile.',
        'You have the best laugh',
        'I love you voice.',
        'You look fantastic!',
        'You have a great sense of humor mate.',
        'If cartoon bluebirds were real, a couple of \'em would be sitting on your shoulders singing right now.',
        'You\'re like sunshine on a rainy day.',
        'You bring out the best in other people!',
        'I bet you sweat glitter.',
        'Colors seem brighter when you\'re around.',
        'You\'re more fun than a ball pit filled with candy.',
        'Jokes are funnier when you tell them.',
        'You always know how to find that silver lining.',
        'You\'re a candle in the darkness.',
        'Being around you is like a happy little vacation.',
        'You\'re more fun than bubble wrap.',
        'You\'re like a breath of fresh air.',
        'You\'re someone\'s reason to smile.',
        'How do you keep being so funny and making everyone laugh?',
        'I like your style!',
        'Is that your picture next to "charming" in the dictionary?',
        'You are brave.',
        'You\'re a great listener.',
        'You\'re inspiring!!',
        'You\'re so thoughtful.',
        'You deserve happiness.',
        'You\'re the type of person everyone wants to be with!',
        'You\'re a smart cookie.',
        'Your ability to recall random factoids at just the right times is impressive.',
        'When you say, "I meant to do that," I totally believe you.',
        'You have the best ideas!',
        'You\'re always learning new things and trying to better yourself. That\'s awesome.',
        'You\'re great at figuring stuff out.',
        'Nothing beats your creativity!',
        'You\'re great at figuring stuff out.',
        'Your creative potential seems limitless.',
        'Everyone gets knocked down sometimes; only people like you get back up again and keep going.',
        'You deserve a hug right now.',
        'You\'re a great example to others.',
        'You\'re an awesome friend.',
        'You\re awesome to be with mate!',
        'You\'re more helpful than you realize.',
        'Hanging out with you is always fun.',
        'Being around you makes everything better.',
        'Someone is getting through something hard right now because you\'ve got their back. Nice work.',
        'The people you love are lucky to have you in their lives.',
        'Any team would be lucky to have you on it!',
        'The way you treasure your loved ones is incredible.',
        'You\'re a gift to those around you.',
        'You\'re gorgeous—and that\'s the least interesting thing about you, too.',
        'You look great today!',
        'How is it that you always look so great, even if you\'re in ratty pajamas?',
        'You may dance like no one\'s watching, but everyone\'s watching because you\'re mesmerizing.',
        'Your hair looks stunning.',
        'Your voice is magnificent.',
        'You\'re irresistible when you blush.',
        'Has anyone ever told you that you have great posture?',
        'On a scale from 1 to 10, you\'re an 11.',
        'Everything would be better if more people were like you.',
        'You\'re better than a triple-scoop ice cream cone. With sprinkles.',
        'You\'re one of a kind.',
        'You\'re really something special.',
        'Your One Smile Can Make My Day :relieved:',
        'You are very good at seeing the best in people, even when everyone else sees the worst.',
        'You have an adventurous spirit.',
        'I always learn so much from You.',
        'You’re a strong, weet, optimistic, practical, person. Never change that about you.',
        'You always know when to lend a hand.',
        'I like your enthusiasm.',
        'Your positive attitude is infectious.',
        'I like your ideas.',
        'You always know exactly what to say.',
        'Is there anything you CAN’T do?',
        'Even if you were Cloned, You’d Still Be One Of A Kind. And The Better-Looking One.',
        'You Are More Unique And Wonderful Than The Smell Of A New Book.',
        'You’re amazing, and I can’t say that enough.',
        'I am so glad we met!',
        'You’re my support system.',
        'I can trust you with all my secrets.',
        'You are really good at what you do.',
        'You amaze us with your hard work.',
        'We don’t want to lose you.',
        'You’re the best.',
        'Out of all the people\'s i\'ve met, you\'re the best one!',
        'I’ll always cherish your valuable advice.',
        'We appreciate you just the way you are.',
        'You are so humble.',
        'You are a blessing from above!',
        'You have a heart of gold! :sparkling_heart:',
        'You have the whitest teeth. Or the best smile of all time!',
        'You have the most interesting perspectives.',
        'I see greatness in you.',
        'Everyone loves you!',
        'Never stop being you!',
        'Spending time with you is the best use of time.',
        'You are so incredibly selfless.',
        'You are a handsome boy!',
        'You are a beautiful girl!',
        'You constantly impress me.',
        'You are the best person I know!',
        'Michael Jackson\'s move\'s has no match for yours!',
        'Anything is possible.',
        'You could be president one day!'
    ]
    return random.choice(Compliments).lower().capitalize()

def Flirt():
    """
    Gives a random flirty pick up line.
    @example
    print(Communication.Flirt())
    """

    Flirts = [
        'No Matter How Horrible My Day Went, When You Smile You Just Made Everything All Right.',
        'You’re Like A Twister, You Just Blow Me Away.',
        'Could You Stop Being So Lovely? You’re Driving Me So Crazy.',
        'I Wonder How My Life Would Be If I Hadn’t Met You.',
        'There Isn’t A Word In The Dictionary That Can Explain Your Type Of Beauty.',
        'Of All Your Beautiful Curves, Your Smile Is My Favorite One.',
        'I’m Trying My Best To Fall Asleep, But I Just Can’t Stop Thinking About You.',
        'I Just Saw The New Picture You Uploaded. Looking Hotter Than Ever, I See.',
        'Seeing Your Name Pop Up On My Phone Screen Makes Me Grin Like An Idiot.',
        'I Have So Much To Do, But I Keep Getting Distracted Thinking About You.',
        'Ugh, I Have A Problem I Can’t Stop Thinking About You.',
        'How Is The Most Beautiful Woman On The Earth Doing This Morning?',
        'I Hope Your Day Is As Beautiful As You.',
        'You Were The First Thing To Come To My Mind As I Woke Up This Morning.',
        'Just The Thought Of You Brightens Up My Morning.',
        'I Wish I Was Waking Up To Your Smile.',
        'I Bet You Look Beautiful Already.',
        'I Hate Good-Nights Because It Means I Am Praising The Time You Spend Away From Me. What I Want To Truly Say, Is That I Can’t Wait To See You Again.',
        'I’ll Dream About You If You Dream About Me. Deal?',
        'Wish You Were Here So I Could Hug/Kiss You Goodnight.',
        'You Are The Last Thing On My Mind Before I Go To Sleep.',
        'I Wish I Was There To Hold You Tight, Instead Of Just Sending You This Loving “Good Night”.',
        'You Are On My Mind So Much That I Thought I Would Text You To Tell You Goodnight.',
        'My Face Hurts From All The Smiling I’ve Done Thinking About YOU. Good Night.',
        'You Are Turning Me Into An Insomniac!',
        'Trying To Fall Asleep…Can’t Stop Thinking About You.',
        'If I Was There You Would Find Out What It Really Means To Be Cozy Under The Covers Sweet Dreams.',
        'Still Working Away, But I Wanted To Take A Break To Say Good Night To The Prettiest Girl In My Life.',
        'Having Trouble Sleeping Because I Need To Tell You I Miss And Love You.',
        'You Are My Everything, Never Forget That. Goodnight.',
        'Flirting With You Over Text Is Always Fun, But It Makes It Hard For Me To Lean In And Kiss You.',
        'Send Me A Picture So I Can Send Santa My Wish List.',
        'People Around Me Must Think That I’m Really Drunk Right Now Because I Am So Intoxicated By You.',
        'I Don’t Think You Understand How Important It Is For Me To Hear The Sound Of Your Voice Every Day.',
        'I May Not Be A Photographer But I Sure Can Picture Us Together Forever.',
        'Your Hand Fits In Mine, Like It’s Made Just For Me.',
        'I Never Ever Thought I’d Like You This Much And I Never Planned To Have You On My Mind This Often.',
        'My Life Is Perfect, But It’s Because I Am With You.',
        'When Words Aren’t Enough To Tell You How Great You’ve Been, Remind Me To Come And Kiss You.',
        'I Feel Comfortable Being Myself When I’m Around You.',
        'You’ve Seen Me At My Best And My Worst, Yet Love Me Anyway.',
        'I Really Like Our Friendship, But I Was Thinking… Do You Want To Make It More?',
        'Wish You Were Here. Next To Me.',
        'Are You Ready To Be Swept Off Of Your Feet Anytime Soon?',
        'If I Were The Last Guy On Earth, Would You Date Me?',
        'If I Took You On A Date, Which Place Should I Choose?',
        'Would You Let Me Be Your Genie For An Evening?',
        'I Wanted To Ask You Out, But I Figured I’d Start By Sending You A Text.',
        'Last Night Was Fun. Can’t Wait To See You Again.',
        'Can You Sneak Away For Coffee?',
        'Any Plans Tomorrow After Work? I Might Just Have A Little Idea Up My Sleeve That I’m Sure You’d Like…A Lot.',
        'Can’t Think Of A Good Reason To Go Out For A Celebratory Drink... But I’m Sure It’s Someone’s Birthday, Somewhere Right Now So We Should Toast To That.',
        'Do You Miss Me? Type “Y” For Yes.',
        'I Likeee You. What Are You Going To Do About That?',
        'Stop Sending Me Mixed Signals And Start Sending Me Memes.',
        'My Dog Wanted You To Know That He Misses You.',
        'I Hope You Find My Willingness To Text First Attractive.',
        'Now That I’ve Officially Texted You, I’m Going To Be Obsessively Staring At My Phone, Waiting For It To Beep, So Don’t Keep Me Waiting.',
        'Would You Rather… Get Your Foot Stuck In A Bear Trap Or Hang Out With Me This Weekend?',
        'Hey! Stop Thinking About Me So Much!',
        'You\'re much beautiful than a rose.',
        'Id i had to pick someone to be with, of course i\'ll pick you.'
    ]
    return random.choice(Flirts).lower().capitalize()

def Insult():
    """
    Gives a random insult.
    @example
    print(Communication.Insult())
    """
    Insults = [
        'If you were an inanimate object, you’d be a participation trophy.',
        'You’re not pretty enough to be that dumb.',
        'Take my lowest priority and put yourself beneath it.',
        'People like you are the reason God doesn’t talk to us anymore.',
        'You’re so dense, light bends around you.',
        'I’d love to stay and chat but I’d rather have type-2 diabetes.',
        'I bet you swim with a T-shirt on.',
        'I hope your wife brings a date to your funeral.',
        'If you were a potato you’d be a stupid potato.',
        'Your face looks like it was set on fire and put out with chains.',
        'You are so ugly that when you were born, the doctor slapped your mother.',
        'If I wanted to commit suicide I’d climb to your ego and jump to your IQ.',
        'Everyone that has ever said they love you was wrong.',
        'I don’t have the time or the crayons to explain this to you.',
        'The only difference between you and Hitler is Hitler knew when to kill himself.',
        'You’re dumber than I tell people.',
        'Your face is so oily that I’m surprised America hasn’t invaded yet.',
        'You are the stone in the shoes of humanity.',
        'I’ve forgotten more than you know.',
        'You look like something I drew with my left hand.',
        'You’re about as important as a white crayon.',
        'It\'s better to let someone think you are an Idiot than to open your mouth and prove it.',
        'You have two parts of brain, \'left\' and \'right\'. In the left side, there\'s nothing right. In the right side, there\'s nothing left.',
        'You must have been born on a highway because that\'s where most accidents happen.',
        'I don\'t think you are stupid. You just have a bad luck when thinking.',
        'Don\'t you love nature, despite what it did to you?',
        'I\'m jealous of all the people that haven\'t met you!',
        'I\'m not insulting you. I\'m describing you.',
        'You are so ugly when you looked in the mirror your reflection walked away.',
        'There\'s only one problem with your face, I can see it.',
        'Brains aren\'t everything. In your case they\'re nothing.',
        'We can always tell when you are lying. Your lips move.',
        'The last thing I want to do is hurt you. But it\'s still on the list.',
        'You do realize makeup isn\'t going to fix your stupidity?',
        'Hell is wallpapered with all your deleted selfies.',
        'Calling you an idiot would be an insult to all stupid people.',
        'It is very easy to become a superman, you just have to change the sequence of clothes while wearing.',
        'You\'re so ugly, you scared the hell out of the toilet.',
        'Ordinarily people live and learn. You just live.',
        'I would love to insult you... but that would be beyond the level of your intelligence.',
        'I got in a fight one time with a really big guy, and he said, \"I\'m going to mop the floor with your face." I said, \"You\'ll be sorry.\" He said, \"Oh, yeah? Why?\" I said, \"Well, you won\'t be able to get into the corners very well."',
        'Karma takes too long, I\'d rather beat you up just now.',
        'Keep talking, someday you\'ll say something intelligent!',
        'Oh, what? Sorry. I was trying to imagine you with a personality.',
        'You are not as bad as people say, you are much, much worse',
        'I\'m multi-talented: I can talk and piss you off at the same time.',
        'Shock me, say something intelligent.',
        'Whatever kind of look you were going for, you missed.',
        'I\'ve seen people like you, but I had to pay admission!',
        'You\'re so sad that even Bob the Builder can\'t fix your life.',
        'If ignorance is bliss, you must be the happiest person on earth.',
        'An mistake will say no, are you a mistake?',
        'It\'s scary to think that people like you are graduating from college.',
        'You sound a lot like the Terms and Conditions, that\'s why I don\'t listen to what you have to say.',
        'I can feel my personality turning a dull shade of grey when I talk to you.',
        'The janitor said he took out the trash last night, he must forgot a piece, what are you still doing here?',
        'I\'m already visualising the duct tape across your mouth.',
        'I believe in respect for the dead; in fact, I could only respect you if you WERE dead.',
        'If I could meet my brain the first thing I would probably say is: "It was truly and sincerely horrible working with you."',
        'You are as sharp as a bowling ball.',
        'For those who never forget a face, you are an exception.',
        'It\'s not often that one gets the opportunity to speak about someone intelligent, respected and admired. Unfortunately tonight I have to talk about you.',
        'Ever since I saw you in your family tree I\'ve wanted to cut it down.',
        'If you don\'t like my opinion of you – improve thyself!',
        'Where did you buy your stupidity? Or it was given for free and you took an overdose?',
        'Your forehead is so big you donated it to charity for shelter!',
        'You\'re IQ\'s lower than your shoe size.',
        'Please, keep talking. I always yawn when I am interested.',
        'I\'m trying to imagine you with a personality.',
        'I\'d love to go out with you, but my favorite commercial is on TV.',
        'Your hairline is like Pluto, unreachable.',
        'Save your breath... You\'ll need it to blow up your date.',
        'If I tell you I\'m thinking about you, don\'t get too excited, because I\'m also thinking about nachos.',
        'Did you get a bowl of soup with that haircut?',
        'I\'m not being rude, you\'re just insignificant.',
        '80 % of the brain is fluid. Unfortunately, in your case, it\'s brake fluid.',
        'Look to your left --------------> I said left you idiot!',
        'How are you related to the sun? Because your teeth are the same colour as it.',
        'You should need a license to be that ugly.',
        'If your brain was dynamite, there wouldn\'t be enough to blow your hat off.',
        'You look like somebody stepped on a goldfish.',
        'Are you always this stupid or is today a special occasion?',
        'You are so dimwitted even the blackhole night sky looks brighter than you.',
        'In San Francisco, Halloween is redundant.',
        'Try to use this vacuum, it may help you remove the cobwebs in your mind.',
        'Welcome to Utah: set your watch back 20 years.',
        'You must be some kind of weirdo to like The Doors. I guess People Are Strange.',
        'You\'re about as useful as a bucket without a bottom.',
        'I don\'t care who you are, but if you\'re reading this I still don\'t care.',
        'I haven\'t been ignoring you; I\'ve been prioritizing you.',
        'What\'s the difference between people and tin foil? Tin foil doesn\'t wrinkle as it oldens.',
        'Every time you open your mouth, some idiot starts talking.',
        'Do you want to see something stupid? Look in the mirror!',
        'Your mom just got a ticket when she dropped you off for school.',
        'You want an insult? Right, look at the mirror.',
        'I\'ll never forget the first time we met. But I\'ll keep trying.',
        'When you were born your mom said: "It\'s a treasure.\" Dad said: "Ya let\'s bury."',
        'If brain cells had value, you\'d be broke.',
        'I\'m experiencing heavy call volumes. Please hang up and never call me again.'
    ]
    return random.choice(Insults).lower().capitalize()

def Roast():
    """
    Gives a random comeback.
    @example
    print(Communication.Roast())
    """
    Comebacks = [
        'If I throw a stick, will you leave?',
        'You’re a gray sprinkle on a rainbow cupcake.',
        'If your brain was dynamite, there wouldn’t be enough to blow your hat off.',
        'You are more disappointing than an unsalted pretzel.',
        'Light travels faster than sound, which is why you seemed bright until you spoke.',
        'Your secrets are always safe with me. I never even listen when you tell me them.',
        'I forgot the world revolves around you. My apologies! How silly of me.',
        'Hold still. I’m trying to imagine you with a personality.',
        'Your face makes onions cry.',
        'I thought of you today. It reminded me to take out the trash.',
        'I’m not a nerd; I’m just smarter than you.',
        'You are like a cloud. When you disappear, it’s a beautiful day.',
        'When you look in the mirror, say hi to the clown you see in there for me, would you?',
        'Wish I had a flip phone so I could slam it shut on this conversation.',
        'You bring everyone so much joy, you know, when you leave the room. But, still.',
        'You have an entire life to be an idiot. Why not take today off?',
        'I’d give you a nasty look, but you’ve already got one.',
        'Life is full of disappointments, and I just added you to the list.',
        'I don’t have the energy to pretend like you today.',
        'The trash gets picked up tomorrow, get ready.',
        'Stupidity isn’t a crime, so you’re free to go.',
        'Too bad you can’t Photoshop your ugly personality.',
        'If laughter is the best medicine, your face must be curing the world.',
        'You’re not stupid, You just have bad luck when you’re thinking.',
        'I’m not insulting you, I’m describing you.',
        'Jealousy is a disease. Get well soon.',
        'I told a therapist about you.',
        'If you were an inanimate object, you’d be a participation trophy.',
        'Do yourself a favor and ignore anyone who tells you to be yourself. Bad idea in your case.',
        'If I ever said anything to offend you, it was purely intentional.',
        'You’re someone that I would draw with my left hand.',
        'Shock me, say something intelligent.',
        'Damn not you again.',
        'It’s too bad stupidity isn’t painful.',
        'Ordinarily peoples lives and learns. You just live.',
        '||I need you,|| ||i want you,|| ||to go away.||',
    ]
    return random.choice(Comebacks).lower().capitalize()