import random

Compliments = [
    'Your smile is contagious.',
    'I bet you make babies smile.',
    'You have the best laugh',
    'I love you voice.',
    'You look fantastic!',
    'You have a great sense of humor mate.',
    'If cartoon bluebirds were real, a couple of \'em would be sitting on your shoulders singing right now.',
    'You\'re like sunshine on a rainy day.',
    'You bring out the best in other people!',
    'I bet you sweat glitter.',
    'Colors seem brighter when you\'re around.',
    'You\'re more fun than a ball pit filled with candy.',
    'Jokes are funnier when you tell them.',
    'You always know how to find that silver lining.',
    'You\'re a candle in the darkness.',
    'Being around you is like a happy little vacation.',
    'You\'re more fun than bubble wrap.',
    'You\'re like a breath of fresh air.',
    'You\'re someone\'s reason to smile.',
    'How do you keep being so funny and making everyone laugh?',
    'I like your style!',
    'Is that your picture next to "charming" in the dictionary?',
    'You are brave.',
    'You\'re a great listener.',
    'You\'re inspiring!!',
    'You\'re so thoughtful.',
    'You deserve happiness.',
    'You\'re the type of person everyone wants to be with!',
    'You\'re a smart cookie.',
    'Your ability to recall random factoids at just the right times is impressive.',
    'When you say, "I meant to do that," I totally believe you.',
    'You have the best ideas!',
    'You\'re always learning new things and trying to better yourself. That\'s awesome.',
    'You\'re great at figuring stuff out.',
    'Nothing beats your creativity!',
    'You\'re great at figuring stuff out.',
    'Your creative potential seems limitless.',
    'Everyone gets knocked down sometimes; only people like you get back up again and keep going.',
    'You deserve a hug right now.',
    'You\'re a great example to others.',
    'You\'re an awesome friend.',
    'You\re awesome to be with mate!',
    'You\'re more helpful than you realize.',
    'Hanging out with you is always fun.',
    'Being around you makes everything better.',
    'Someone is getting through something hard right now because you\'ve got their back. Nice work.',
    'The people you love are lucky to have you in their lives.',
    'Any team would be lucky to have you on it!',
    'The way you treasure your loved ones is incredible.',
    'You\'re a gift to those around you.',
    'You\'re gorgeous—and that\'s the least interesting thing about you, too.',
    'You look great today!',
    'How is it that you always look so great, even if you\'re in ratty pajamas?',
    'You may dance like no one\'s watching, but everyone\'s watching because you\'re mesmerizing.',
    'Your hair looks stunning.',
    'Your voice is magnificent.',
    'You\'re irresistible when you blush.',
    'Has anyone ever told you that you have great posture?',
    'On a scale from 1 to 10, you\'re an 11.',
    'Everything would be better if more people were like you.',
    'You\'re better than a triple-scoop ice cream cone. With sprinkles.',
    'You\'re one of a kind.',
    'You\'re really something special.',
    'Your One Smile Can Make My Day :relieved:',
    'You Are Very Good At Seeing The Best In People, Even When Everyone Else Sees The Worst.',
    'You Have An Adventurous Spirit.',
    'I Always Learn So Much From You.',
    'Talking To You Is So Refreshing. I’m Happy That We Can Communicate Like This All The Time.',
    'You’re A Strong, Sweet, Optimistic, Practical, Woman or Men. Never Change That About You.',
    'You Always Know When To Lend A Hand.',
    'I Love Your Enthusiasm!',
    'Your Positive Attitude Is Infectious.',
    'I Love Your Ideas!',
    'You Always Know Exactly What To Say.',
    'You Really Know How To Treat A Woman.',
    'Is There Anything You CAN’T Do?',
    'You Were Cool Way Before Hipsters Were Cool!',
    'Hanging Out With You Is Always A Blast.',
    'Everyone would want to have you in a party!',
    'Even If You Were Cloned, You’d Still Be One Of A Kind. And The Better-Looking One.',
    'You Are More Unique And Wonderful Than The Smell Of A New Book.',
    'You’re amazing, and I can’t say that enough.',
    'I am so glad we met!',
    'You’re my support system.',
    'I can trust you with all my secrets.',
    'You are really good at what you do.',
    'You amaze us with your hard work.',
    'We don’t want to lose you.',
    'You’re the best.',
    'Out of all the people\'s i\'ve met, you\'re the best one!',
    'I’ll always cherish your valuable advice.',
    'We appreciate you just the way you are.',
    'You are so humble.',
    'You are a blessing from above!',
    'You have a heart of gold! :sparkling_heart:',
    'You have the whitest teeth. Or the best smile of all time!',
    'You have the most interesting perspectives.',
    'I see greatness in you.',
    'Everyone loves you!',
    'Never stop being you!',
    'Spending time with you is the best use of time.',
    'You are so incredibly selfless.',
    'You are a handsome boy!',
    'You are a beautiful girl!',
    'You constantly impress me.',
    'You are the best person I know!',
    'Michael Jackson\'s move\'s has no match for yours!',
    'Anything is possible.',
    'You could be president one day!',
]

def Compliment():
    return random.choice(Compliments)